#!/usr/bin/env bash
# Script that pings an IP address passed as an argument

# IP variable
IP="${1}"

# File name variable
fn=$(basename "${BASH_SOURCE[0]}")

# Check if IP is provided
if [ -z "$IP" ]; then
    echo "Usage: ${fn} {IP_ADDRESS}"
    exit 1
else
    # Ping the IP 5 times
    ping -c 5 "${IP}"
fi
